services:
  - type: web
    name: bench-backend
    env: java # Correct runtime for Java/Spring
    rootDir: Bench-Management-Backend
    branch: main
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/*.jar
    plan: free
    envVars:
      # Database variables
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: bench-management
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: bench-management
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: bench-management
          property: password
      
      # JWT variables
      - key: JWT_SECRET
        value: YjdhN2h1QWVkM3RhX2VJY3EyMG1yb2JhWWNfR1FkWldkOVB3Q0ZrcEVlc2Vlc1U=nYjdhN2h1QWVkM3RhX2VJY3EyMG1yb2JhWWNfR1FkWldkOVB3Q0ZrcEVlc2Vlc1U=
      - key: JWT_EXPIRATION
        value: 86400000
