services:
  - type: web
    name: bench-backend
    env: docker
    # Tells Render to run the build inside this folder
    rootDir: ./bench-backend
    plan: free
    # Path to the Dockerfile from the repository root
    dockerfilePath: ./bench-backend/Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: bench-management
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: bench-management
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: bench-management
          property: password
      - key: JWT_SECRET
        fromGroup: enviroment # Assuming your group is named 'enviroment'
      - key: JWT_EXPIRATION
        value: 86400000
