services:
  - type: web
    name: bench-backend
    env: spring
    rootDir: Bench-Management-Backend
    branch: main
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/*.jar
    plan: free
    
    # Links your JWT_SECRET from the Environment Group
    envVarGroups:
      - name: enviroment 

    # Connects to your database service named "bench-management"
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: bench-management # <-- Correct service name
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: bench-management # <-- Correct service name
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: bench-management # <-- Correct service name
          property: password
