services:
  - type: web
    name: bench-backend
    env: spring
    rootDir: Bench-Management-Backend
    branch: main
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/*.jar
    plan: free
    envVarGroups:
      - name: enviroment
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: bench-management
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: bench-management
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: bench-management
          property: password
