services:
  - type: web
    name: bench-backend
    rootDir: Bench-Management-Backend
    branch: main
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/*.jar
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://<RENDER_MYSQL_HOST>:3306/benchmgmt?useSSL=false&serverTimezone=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: your_mysql_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: your_mysql_password
      - key: SERVER_PORT
        value: 8080
      - key: JWT_SECRET
        value: your_jwt_secret
      - key: JWT_EXPIRATION
        value: 86400000
