services:
  - type: web
    name: bench-backend
    env: docker
    rootDir: ./bench-backend
    plan: free
    dockerfilePath: ./bench-backend/Dockerfile
    envVars:
      # 1. Pull Render's URL into a temporary variable
      - key: DB_CONNECTION_STRING 
        fromDatabase:
          name: bench-management
          property: connectionString
      
      # 2. Build the correct JDBC URL for Spring
      - key: SPRING_DATASOURCE_URL 
        value: jdbc:${DB_CONNECTION_STRING}

      # These are still needed for Spring's auto-configuration
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: bench-management
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: bench-management
          property: password

      # Your other variables
      - key: JWT_SECRET
        fromGroup: enviroment
      - key: JWT_EXPIRATION
        value: 86400000
